apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fmjoif3kd-nodejs
  janus-idp.io/tekton: fmjoif3kd-nodejs
  backstage.io/kubernetes-id: fmjoif3kd-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fmjoif3kd-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
